## Regresion lineal

#### Objetivo: ¿Qué regiones muestran costos mayores tras controlar por edad, BMI y número de hijos?

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./data/insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
df.sample(5)

      age     sex    bmi  children smoker     region      charges
754    24    male  33.63         4     no  northeast  17128.42608
614    20  female  33.00         0     no  southeast   1880.07000
1011   43    male  20.13         2    yes  southeast  18767.73770
172    18    male  15.96         0     no  northeast   1694.79640
159    50  female  27.83         3     no  southeast  19749.38338

In [5]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1)

In [7]:
df['region'].value_counts(dropna=False)

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64